title: My Little Webpage
author: Amanda
theme:minima 
email: AmandaC0022@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a little webpage I am building for a project in class. 

# social links
github_username:  @AmandaC0022 

show_excerpts: true # set to false to remove excerpts on the homepage
